In [1]:
import numpy as np

In [2]:
y = np.array([5,6,7,8,9,10])

In [3]:
y

array([ 5,  6,  7,  8,  9, 10])

In [4]:
y.dtype

dtype('int32')

In [5]:
z=np.array([6,5,4,3,2,1])
z

array([6, 5, 4, 3, 2, 1])

In [6]:
z=(y+z)/11
z

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
r = np.random.random((1,10))
r

array([[ 0.20534071,  0.13155347,  0.90587149,  0.71137358,  0.23394744,
         0.32105315,  0.5139735 ,  0.23359935,  0.03180402,  0.76626783]])

In [8]:
type(z)

numpy.ndarray

In [9]:
z.dtype

dtype('float64')

In [10]:
type(r)

numpy.ndarray

In [11]:
s = np.random.random((10,2))
s

array([[ 0.33584732,  0.77595064],
       [ 0.19164642,  0.50368717],
       [ 0.54246378,  0.45389962],
       [ 0.35136187,  0.98671755],
       [ 0.67294699,  0.10950306],
       [ 0.70613549,  0.96053284],
       [ 0.83868204,  0.72198826],
       [ 0.10282418,  0.75422375],
       [ 0.55956021,  0.25221392],
       [ 0.9148752 ,  0.93437959]])

In [12]:
type(s)

numpy.ndarray